//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Storage.Table
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TableEntity", Namespace = "http://schemas.datacontract.org/2004/07/Microsoft.WindowsAzure.Storage.Table")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceInterface.CustomerEntity))]
    public partial class TableEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ETagField;

        private string PartitionKeyField;

        private string RowKeyField;

        private System.DateTimeOffset TimestampField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ETag
        {
            get
            {
                return this.ETagField;
            }
            set
            {
                this.ETagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RowKey
        {
            get
            {
                return this.RowKeyField;
            }
            set
            {
                this.RowKeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
}
namespace System
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DateTimeOffset", Namespace = "http://schemas.datacontract.org/2004/07/System")]
    public partial struct DateTimeOffset : System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime DateTimeField;

        private short OffsetMinutesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public short OffsetMinutes
        {
            get
            {
                return this.OffsetMinutesField;
            }
            set
            {
                this.OffsetMinutesField = value;
            }
        }
    }
}
namespace ServiceInterface
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CustomerEntity", Namespace = "http://schemas.datacontract.org/2004/07/ServiceInterface")]
    public partial class CustomerEntity : Microsoft.WindowsAzure.Storage.Table.TableEntity
    {

        private string EmailField;

        private string PhoneNumberField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IWorkerService")]
public interface IWorkerService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkerService/CreateAzureTable", ReplyAction = "http://tempuri.org/IWorkerService/CreateAzureTableResponse")]
    bool CreateAzureTable(string tableName);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkerService/CreateAzureTable", ReplyAction = "http://tempuri.org/IWorkerService/CreateAzureTableResponse")]
    System.Threading.Tasks.Task<bool> CreateAzureTableAsync(string tableName);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkerService/InsertEntityToAzureTable", ReplyAction = "http://tempuri.org/IWorkerService/InsertEntityToAzureTableResponse")]
    bool InsertEntityToAzureTable(string tableName, ServiceInterface.CustomerEntity entity);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkerService/InsertEntityToAzureTable", ReplyAction = "http://tempuri.org/IWorkerService/InsertEntityToAzureTableResponse")]
    System.Threading.Tasks.Task<bool> InsertEntityToAzureTableAsync(string tableName, ServiceInterface.CustomerEntity entity);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkerService/GetEntitiesFromAzureTableUsingPartitionKey", ReplyAction = "http://tempuri.org/IWorkerService/GetEntitiesFromAzureTableUsingPartitionKeyRespo" +
        "nse")]
    ServiceInterface.CustomerEntity[] GetEntitiesFromAzureTableUsingPartitionKey(string tableName, string partitionKey);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkerService/GetEntitiesFromAzureTableUsingPartitionKey", ReplyAction = "http://tempuri.org/IWorkerService/GetEntitiesFromAzureTableUsingPartitionKeyRespo" +
        "nse")]
    System.Threading.Tasks.Task<ServiceInterface.CustomerEntity[]> GetEntitiesFromAzureTableUsingPartitionKeyAsync(string tableName, string partitionKey);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkerService/GetShortMachineInformation", ReplyAction = "http://tempuri.org/IWorkerService/GetShortMachineInformationResponse")]
    string GetShortMachineInformation();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkerService/GetShortMachineInformation", ReplyAction = "http://tempuri.org/IWorkerService/GetShortMachineInformationResponse")]
    System.Threading.Tasks.Task<string> GetShortMachineInformationAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWorkerServiceChannel : IWorkerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WorkerServiceClient : System.ServiceModel.ClientBase<IWorkerService>, IWorkerService
{

    public WorkerServiceClient()
    {
    }

    public WorkerServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public WorkerServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public WorkerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public WorkerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public bool CreateAzureTable(string tableName)
    {
        return base.Channel.CreateAzureTable(tableName);
    }

    public System.Threading.Tasks.Task<bool> CreateAzureTableAsync(string tableName)
    {
        return base.Channel.CreateAzureTableAsync(tableName);
    }

    public bool InsertEntityToAzureTable(string tableName, ServiceInterface.CustomerEntity entity)
    {
        return base.Channel.InsertEntityToAzureTable(tableName, entity);
    }

    public System.Threading.Tasks.Task<bool> InsertEntityToAzureTableAsync(string tableName, ServiceInterface.CustomerEntity entity)
    {
        return base.Channel.InsertEntityToAzureTableAsync(tableName, entity);
    }

    public ServiceInterface.CustomerEntity[] GetEntitiesFromAzureTableUsingPartitionKey(string tableName, string partitionKey)
    {
        return base.Channel.GetEntitiesFromAzureTableUsingPartitionKey(tableName, partitionKey);
    }

    public System.Threading.Tasks.Task<ServiceInterface.CustomerEntity[]> GetEntitiesFromAzureTableUsingPartitionKeyAsync(string tableName, string partitionKey)
    {
        return base.Channel.GetEntitiesFromAzureTableUsingPartitionKeyAsync(tableName, partitionKey);
    }

    public string GetShortMachineInformation()
    {
        return base.Channel.GetShortMachineInformation();
    }

    public System.Threading.Tasks.Task<string> GetShortMachineInformationAsync()
    {
        return base.Channel.GetShortMachineInformationAsync();
    }
}
